spring:
  profiles:
    default: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://158.179.173.21:3306/sodong
    username: chjung99
    password: cksgh1168

  jpa:
    open-in-view:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50

server:
  port: 8081